default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gist_mailer_dev
test:
  <<: *default
  database: gist_mailer_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
